on:
  pull_request:
  push:
    branches:
    - main
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v5
      with:
        node-version: "22.12.0"
    - run: |
       npm install
       ./format.sh
       git diff --exit-code
    - uses: actions/setup-java@v5
      with:
        java-version: 8
        distribution: temurin
    - uses: sbt/setup-sbt@v1
    - run: sbt -v
           scalafmtSbtCheck
           scalafmtCheckAll
           javafmtCheckAll
           test
           dist
    - uses: actions/upload-pages-artifact@v4
      if: (github.event_name == 'push') && (github.ref == 'refs/heads/main')
      with:
        path: sources
  deploy:
    needs: test
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'xuwei-k' && github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    steps:
    - uses: actions/deploy-pages@v4
